export default {
  "response": {
  "version":"0.1",
  "termsofService":"http://www.wunderground.com/weather/api/d/terms.html",
  "features": {
  "conditions": 1
  }
	}
  ,	"current_observation": {
		"image": {
		"url":"http://icons.wxug.com/graphics/wu2/logo_130x80.png",
		"title":"Weather Underground",
		"link":"http://www.wunderground.com"
		},
		"display_location": {
		"full":"Denver, CO",
		"city":"Denver",
		"state":"CO",
		"state_name":"Colorado",
		"country":"US",
		"country_iso3166":"US",
		"zip":"80201",
		"magic":"1",
		"wmo":"99999",
		"latitude":"39.74000168",
		"longitude":"-104.98000336",
		"elevation":"1598.1"
		},
		"observation_location": {
		"full":"San Rafael Neighborhood, Denver, Colorado",
		"city":"San Rafael Neighborhood, Denver",
		"state":"Colorado",
		"country":"US",
		"country_iso3166":"US",
		"latitude":"39.751591",
		"longitude":"-104.977402",
		"elevation":"5253 ft"
		},
		"estimated": {
		},
		"station_id":"KCODENVE131",
		"observation_time":"Last Updated on July 26, 2:10 PM MDT",
		"observation_time_rfc822":"Wed, 26 Jul 2017 14:10:15 -0600",
		"observation_epoch":"1501099815",
		"local_time_rfc822":"Wed, 26 Jul 2017 14:16:09 -0600",
		"local_epoch":"1501100169",
		"local_tz_short":"MDT",
		"local_tz_long":"America/Denver",
		"local_tz_offset":"-0600",
		"weather":"Mostly Cloudy",
		"temperature_string":"76.4 F (24.7 C)",
		"temp_f":76.4,
		"temp_c":24.7,
		"relative_humidity":"59%",
		"wind_string":"Calm",
		"wind_dir":"North",
		"wind_degrees":360,
		"wind_mph":0.7,
		"wind_gust_mph":"4.5",
		"wind_kph":1.1,
		"wind_gust_kph":"7.2",
		"pressure_mb":"1017",
		"pressure_in":"30.02",
		"pressure_trend":"-",
		"dewpoint_string":"61 F (16 C)",
		"dewpoint_f":61,
		"dewpoint_c":16,
		"heat_index_string":"NA",
		"heat_index_f":"NA",
		"heat_index_c":"NA",
		"windchill_string":"NA",
		"windchill_f":"NA",
		"windchill_c":"NA",
		"feelslike_string":"76.4 F (26 C)",
		"feelslike_f":"76.4",
		"feelslike_c":"26",
		"visibility_mi":"10.0",
		"visibility_km":"16.1",
		"solarradiation":"--",
		"UV":"6","precip_1hr_string":"0.00 in ( 0 mm)",
		"precip_1hr_in":"0.00",
		"precip_1hr_metric":" 0",
		"precip_today_string":"0.00 in (0 mm)",
		"precip_today_in":"0.00",
		"precip_today_metric":"0",
		"icon":"mostlycloudy",
		"icon_url":"http://icons.wxug.com/i/c/k/mostlycloudy.gif",
		"forecast_url":"http://www.wunderground.com/US/CO/Denver.html",
		"history_url":"http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KCODENVE131",
		"ob_url":"http://www.wunderground.com/cgi-bin/findweather/getForecast?query=39.751591,-104.977402",
		"nowcast":""
	}
}
